#hw.nvidiadrm.modeset=1 # nvidia drm harus load saat boot
security.bsd.allow_destructive_dtrace=0
#snd_driver_load="YES"
hw.psm.synaptics_support="1"
ext2fs_load="YES" 	# to automatic load linux ext4 partiion

# copas dari config freebsd x220
# set no time loading booting    
autoboot_delay=0    
# enable core temp sensor    
coretemp_load="YES"    
# enable in memory file system    
tmpfs_load="YES"    
# enable asyncronous I/O    
aio_load="YES"    
############################   
boot_mute="YES"

